### ISSUE TITLE
404 error: can't find octicons.woff

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#104]
When I open https://ldionne.github.io/metabench and look at the console, I see an error 

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (octicons.woff, line 0)
```

**Comment by ldionne** [comment]
Is it just a matter of placing `octicons.woff` at the root, or is it hiding a deeper problem?

**Comment by brunocodutra** [comment]
> Is it just a matter of placing octicons.woff at the root

Yes.

> is it hiding a deeper problem?

Not at all, I deliberately decided not to add it since we already provide `.eot` for IE and `.ttf` for all other browsers, but since browsers complain, we should probably add it then. BTW, I also didn't add the `.svg` file, so perhaps after we fix the missing `.woff` it will start complaining about it. See https://github.com/github/octicons/blob/master/octicons/octicons.css#L3.
