### ISSUE TITLE
metabench last updated May 30

### ISSUE THREAD

**Issue by ericniebler** [ldionne/metabench#125]
Seems the nightly that is pushing results to http://ldionne.com/metabench is stalled.

**Comment by ldionne** [comment]
That's because LLVM took down its mirrors. That thing is very annoying; I can't imagine how many open source projects are broken by this.

**Comment by ericniebler** [comment]
Agreed. Is there an alternative?

**Comment by ldionne** [comment]
I don't know any. It's breaking all of my builds (Hana too), but they said they would provide a solution soon so I'm waiting.

**Comment by ldionne** [comment]
I'm installing the compiler manually. It's a build for Ubuntu 14.04, but it appears to work on Ubuntu 12.xx too.

**Comment by brunocodutra** [comment]
Do you think we could do the same for [gcc-6 (6.1.1-3ubuntu11~12.04.1)](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test)?

**Comment by ldionne** [comment]
I guess that would be possible, but I failed to find prebuilt GCC binaries for Ubuntu (like a tarball, not an apt package that would require `sudo` to install).

**Comment by ericniebler** [comment]
I've been told that Docker images are the way to go for this, but I haven't looked into it.

**Comment by brunocodutra** [comment]
> I guess that would be possible, but I failed to find prebuilt GCC binaries for Ubuntu  (like a tarball, not an apt package that would require sudo to install).

An APT package just an `ar` archive that among other things contains a tarball called `data.tar.gz` which in turn contains the file to be installed in their respective directories relative to `/`.

Since there seems to be a GCC 6 APT package for precise, I believe it would be just a matter of extracting the contents and executing locally.

**Comment by badair** [comment]
FYI, [here](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html) is the rationale from the LLVM project.

> It's breaking all of my builds (Hana too), but they said they would provide a solution soon so I'm waiting

@ldionne if you hear more about a ready-made solution, would you mind leaving a comment here (if you can remember)?

Editing travis yml scripts takes me a very long time, since the only debug method I know is to commit and wait. Maybe I'm doing it wrong.

**Comment by ldionne** [comment]
@ericniebler Perhaps Docker is the way to go, but I think Travis's support for it is still experimental. Plus, I don't know much about Docker so installing tarballs is much easier for me.

@brunocodutra Ah, I didn't know that about apt packages. I'll have a look.

@badair Thanks for the link. As for the ready-made solution, I would say just copy/paste what I did here for Clang or what I did for Hana [here](https://github.com/boostorg/hana/commit/f08e824a34cc). That, or wait for Travis to workaround it on their side, or wait for the LLVM mirrors to be back up (if they ever come back up). For debugging travis, commit and wait is the only way I know too, but you can make the wait shorter by disabling the parts of your script that you are not testing when you're experimenting.

**Comment by badair** [comment]
@ldionne Okay, thanks. By the way, another way to add GCC 6 CI would be to use Appveyor/Windows in conjunction with [Lavavej's MinGW GCC 6.1 distro](https://nuwen.net/mingw.html). It's only 37 MB.
