### ISSUE TITLE
Provide benchmarks on GCC 6

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#126]
@brunocodutra In [this comment](https://github.com/ldionne/metabench/issues/125#issuecomment-225195959) of #125, you say

> Do you think we could do the same for gcc-6 (6.1.1-3ubuntu11~12.04.1)?

However, I can't find what's the URL for getting a tarball from the GCC apt-repo you linked to. If you can provide an URL that I can `wget`, I'll try to setup CI on GCC.

**Comment by brunocodutra** [comment]
It turns out gcc 6 [made it into](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+index?field.series_filter=precise) `ubuntu-toolchain-r/test` for precise as well.

While we wait on travis-ci/apt-package-whitelist#2294, I think we can download it directly [here](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/9734443). More specifically, I think we are interested in the following packages:

* [gcc-6-base_6.1.1-3ubuntu11~12.04.1_amd64](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/9734443/+files/gcc-6-base_6.1.1-3ubuntu11~12.04.1_amd64.deb)
* [gcc-6_6.1.1-3ubuntu11~12.04.1_amd64](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/9734443/+files/gcc-6_6.1.1-3ubuntu11~12.04.1_amd64.deb)
* [g++-6_6.1.1-3ubuntu11~12.04.1_amd64](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/9734443/+files/g++-6_6.1.1-3ubuntu11~12.04.1_amd64.deb)
* [libstdc++-6-dev_6.1.1-3ubuntu11~12.04.1_amd64](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/9734443/+files/libstdc++-6-dev_6.1.1-3ubuntu11~12.04.1_amd64.deb)
