### ISSUE TITLE
Negative values on y axis

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#157]
Some graphs show negative Y values (or `-0.0` values??), especially for small numbers of elements:

![screen shot 2016-10-30 at 12 35 42](https://cloud.githubusercontent.com/assets/700834/19839371/9dbd725e-9e9d-11e6-8e9b-4a6226e9d32b.png)

These negative values used to be all around because we had a very bad resolution, so it wasn't really a _bug_ (just a symptom of bad resolution). Now, with the resolution that we have, these negative values should be rare and we might want to start considering them as undesirable.

We could either force the graph to show negative values as zero, or redo measurements when we get a negative value. I looked into using `chart.yAxis.scale().domain(...)`, but no luck.

**Comment by brunocodutra** [comment]
First of all, I think it makes sense to use milliseconds on the `y` axis now that we have better measurements.

Regarding restricting the domain of the `y` axis, you are actually looking for `chart.yDomain([0, max])`. Things are not that simple however, because AFAICT we must always limit both the lower and the upper bound and computing `max` is actually tricky, because it depends on the `ASPECT` and also on whether the user wishes to subtract the baseline or not.

**Comment by brunocodutra** [comment]
It would probably be much easier to manually fix negative values to zero by defining `chart.y` accordingly.
Something like `chart.y(function(datum){ max(0, ...) })`

**Comment by ldionne** [comment]
> It would probably be much easier to manually fix negative values to zero by defining chart.y accordingly.

I was reluctant with this approach because it means twiddling with the actual data, but I guess it's not a big deal. I'll do this.
