### ISSUE TITLE
Unable to Benchmark When Cross Compiling

### ISSUE THREAD

**Issue by ricejasonf** [ldionne/metabench#181]
It appears that metabench.rb attempts to execute the target to benchmark the execution time. If there is an error with this everything fails. With cross-compiling this is an issue because the target might not be able to execute on the same system.

In my case the target is a javascript file. I'm trying to measure compile-time and file size of javascript generated with the Emscripten compiler, but I get the following error:

```
stderr
--------------------------------------------------------------------------------
sh: 1: /opt/build/_metabench/create_obj_emval.js: Permission denied
```

Can we add a flag or something  to disable execution for these scenarios?
(or perhaps just remove it altogether :smile: )

I'm available to make a PR for this if given guidance on the best course of action.

**Comment by ldionne** [comment]
I actually don't know what the best course of action should be. Perhaps what we could do is to not report an error and just take note of that in the dataset, e.g. the dataset would contain the error instead of the execution time. We could then see that execution was an error if we ever try to look at the graph in a browser. Another possibility is to do as you say and give more control to the user over what's being executed (or not executed).

**Comment by ricejasonf** [comment]
fwiw, I had this working on my end in a script that just deleted the corresponding lines in the metabench.cmake file... can't seem to find it now.

**Comment by ldionne** [comment]
I know this can be "hacked" to work easily, but I'd like to find a clean way to support this.
