### ISSUE TITLE
[gh-pages] Should we smooth benchmark results?

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#69]
Right now charts are displayed exactly as measured and are thus subject to variations related to thread scheduling and other SO affairs that result in undesirable spikes. 

Activating [`basis` or `bundle` interpolation on NVD3](http://www.d3noob.org/2013/01/smoothing-out-lines-in-d3js.html) should smooth out most spikes.

**Comment by ldionne** [comment]
I guess we can try it out, but I would be tempted to think that we should show raw data and document how the benchmarks are gathered (on Travis CI instances, etc...). This way, people can apply some kind of filter on the results they see.

If it makes the charts much easier to visualize, however, then it might be worth it.

**Comment by brunocodutra** [comment]
Raw data will always be available through the JSON files and also even in the source file of the HTML files, as data manipulation would be carried out by javascript.

**Comment by ldionne** [comment]
Ok, then let's try it out.

**Comment by ldionne** [comment]
BTW, should we publish the JSON files too? I think it makes sense to do so.

**Comment by brunocodutra** [comment]
Yes, ideally we should provide some public API that others could use load benchmark data dynamically into their projects, something in the lines of [GH's API](https://developer.github.com/v3/), but I have no idea how to accomplish that or even if it is possible at all in our current setup.

**Comment by brunocodutra** [comment]
I've been experimenting with interpolation locally and while it improves the situation, spikes are still quite noticeable.

Compare raw values
![raw](https://cloud.githubusercontent.com/assets/4043663/14082535/e72a0b7a-f4e6-11e5-9567-b30706a3fe34.png)

with D3 `basis` interpolation
![interpolated](https://cloud.githubusercontent.com/assets/4043663/14082528/e13dfa50-f4e6-11e5-9314-bb303f1d8c8d.png)

What do you think?

**Comment by brunocodutra** [comment]
BTW, what could be the cause of the severe spikes in the benchmarks of Fusion and MPL? I suspect the preprocessor could be the culprit? Would there be any way to  mitigate this? 

How about we repeat each compilation step a couple of times (3) and take the median value as the actual benchmark? I understand benchmarking would take a couple of times (3) longer, but do we care? Are we near blowing up Travis limits? 

Perhaps it would be a good idea to reduce the number of samples and increase the number of times we repeat each step.

**Comment by ldionne** [comment]
> Compare raw values 
> [...]
>
> with D3 basis interpolation
> [...]
> 
> What do you think?

I think the difference in readability is not really big. Since having a smooth curve for a fundamentally discrete function is a bit strange, I would probably leave it with raw values.

> BTW, what could be the cause of the severe spikes in the benchmarks of Fusion and MPL?

Honestly, I don't know. It could also be the fact that MPL/Fusion requires a large number of headers to be read from disk, and that might induce more variability in the results. I don't know for sure. That being said...

> Would there be any way to mitigate this?

I don't think we actually care about this. Fusion/MPL are so far above other libraries that knowing the timings with precision is actually not useful. To me, all that's interesting, is to know that I'm way below Fusion/MPL, but not the exact timings of Fusion/MPL.


> How about we repeat each compilation step a couple of times (3) and take the median value as the actual benchmark? 

I've thought about it for Hana, and my conclusion was that since the graphs are more or less the same each time we generate them, and since we don't really need that much precision, I would not make the data acquisition more complex for a possibly small benefit. 

That being said, it would make sense (and would be more rigorous) to do as you propose. Perhaps we could try it out and see whether it improves the situation.


> I understand benchmarking would take a couple of times (3) longer, but do we care? Are we near blowing up Travis limits?

Right now, with the small number of benchmarks we have, no. But when we'll add more benchmarks, this might become a real problem.


> Perhaps it would be a good idea to reduce the number of samples and increase the number of times we repeat each step.

Again, I think trying it out and seeing is our best option. Personally, I am fond of having a lot of data points, even if they are not repeated many times, but perhaps that's wrong.

**Comment by brunocodutra** [comment]
> > Compare raw values
> > [...]
> > 
> > with D3 basis interpolation
> > [...]
> > 
> > What do you think?
> 
> I think the difference in readability is not really big. Since having a smooth curve for a fundamentally discrete function is a bit strange, I would probably leave it with raw values.

Agreed.

> >BTW, what could be the cause of the severe spikes in the benchmarks of Fusion and MPL?
> 
> Honestly, I don't know. It could also be the fact that MPL/Fusion requires a large number of headers to be read from disk, and that might induce more variability in the results.

That makes sense.

> Would there be any way to mitigate this?
> 
> I don't think we actually care about this.

Actually I'm a bit concerned about lack of reproducibility, that is, benchmark results vary considerably between runs and that might reduce confidence in data produced by metabench.

>> How about we repeat each compilation step a couple of times (3) and take the median value as the actual benchmark? 
>
> Perhaps we could try it out and see whether it improves the situation.

I think it is worth a try.

**Comment by ldionne** [comment]
Fixed by #74.

**Comment by brunocodutra** [comment]
Since microbenchmarks have been introduced, results became specially sensitive the noise imposed by multitasking. To address this annoyance I have been revisiting d3 interpolation locally and I think we should reopen this discussion. I know smoothing benchmarks hides the fact we actually measure just a few samples, but isn't metabench all about *trends* rather than quantitative measurements anways? I really think a smooth line is better representative of a *trend* than edgy lines that cross themselves at multiple positions.

Compare these, which have been taken from [ldionne.com/metabench](http://ldionne.com/metabench/type/clang++-3.8/find_if/index.html) as of today (20/08/16).
![edgy](https://cloud.githubusercontent.com/assets/4043663/17833311/0eefb5b2-66f0-11e6-99f2-e5c98d0a9156.png)
![smooth](https://cloud.githubusercontent.com/assets/4043663/17833310/0eebeb44-66f0-11e6-8c86-341bf64461a2.png)
